port: "8089"

db:
  postgres:
    host: "localhost"
    port: "5432"
    database: "postgres"
    username: "postgres"
    sslMode: "disable"

auth:
  server:
    url: "http://localhost:9099"
    secret: "qrkjk#4#%35FSFJlja#4353KSFjH"